sonar.projectKey=asm_lexer
sonar.working.directory=/home/alexander/Documents/testing-labs/asm_lexer_testing/.sonarqube/out/.sonar
sonar.projectBaseDir=/home/alexander/Documents/testing-labs/asm_lexer_testing
sonar.pullrequest.cache.basepath=/home/alexander/Documents/testing-labs/asm_lexer_testing

F4F8B5A6-061C-48CD-864E-0E84682BD646.sonar.projectKey=asm_lexer:F4F8B5A6-061C-48CD-864E-0E84682BD646
F4F8B5A6-061C-48CD-864E-0E84682BD646.sonar.projectName=asm_lexer_testing
F4F8B5A6-061C-48CD-864E-0E84682BD646.sonar.projectBaseDir=/home/alexander/Documents/testing-labs/asm_lexer_testing
F4F8B5A6-061C-48CD-864E-0E84682BD646.sonar.sourceEncoding=utf-8
F4F8B5A6-061C-48CD-864E-0E84682BD646.sonar.tests=
F4F8B5A6-061C-48CD-864E-0E84682BD646.sonar.sources=\
"/home/alexander/Documents/testing-labs/asm_lexer_testing/LexerTests.cs",\
"/home/alexander/Documents/testing-labs/asm_lexer_testing/Program.cs",\
"/home/alexander/Documents/testing-labs/asm_lexer_testing/.gitignore",\
"/home/alexander/Documents/testing-labs/asm_lexer_testing/test.runsettings",\
"/home/alexander/Documents/testing-labs/asm_lexer_testing/obj/project.assets.json",\
"/home/alexander/Documents/testing-labs/asm_lexer_testing/obj/asm_lexer_testing.csproj.nuget.dgspec.json",\
"/home/alexander/Documents/testing-labs/asm_lexer_testing/.vs/asm_lexer_testing/v17/DocumentLayout.backup.json",\
"/home/alexander/Documents/testing-labs/asm_lexer_testing/.vs/asm_lexer_testing/v17/DocumentLayout.json",\
"/home/alexander/Documents/testing-labs/asm_lexer_testing/bin/Debug/net8.0/asm_lexer_testing.deps.json",\
"/home/alexander/Documents/testing-labs/asm_lexer_testing/bin/Debug/net8.0/asm_lexer_testing.runtimeconfig.json",\
"/home/alexander/Documents/testing-labs/asm_lexer_testing/obj/Debug/net8.0/asm_lexer_testing.sourcelink.json"

F4F8B5A6-061C-48CD-864E-0E84682BD646.sonar.cs.analyzer.projectOutPaths=\
"/home/alexander/Documents/testing-labs/asm_lexer_testing/.sonarqube/out/0"
F4F8B5A6-061C-48CD-864E-0E84682BD646.sonar.cs.roslyn.reportFilePaths=\
"/home/alexander/Documents/testing-labs/asm_lexer_testing/.sonarqube/out/0/Issues.json"
F4F8B5A6-061C-48CD-864E-0E84682BD646.sonar.cs.scanner.telemetry=\
"/home/alexander/Documents/testing-labs/asm_lexer_testing/.sonarqube/out/0/Telemetry.json"

F4F8B5A6-061C-48CD-864E-0E84682BD646.sonar.working.directory=/home/alexander/Documents/testing-labs/asm_lexer_testing/.sonarqube/out/.sonar/mod0
sonar.host.url=http://localhost:9000
sonar.visualstudio.enable=false

sonar.modules=F4F8B5A6-061C-48CD-864E-0E84682BD646

